"""Quantum kernels: estimators, Gram matrices, PSD repair, and kernel models."""

from qmlkit.kernels.estimators import (
    fidelity_kernel,
    hadamard_test,
    inversion_circuit,
    swap_probability,
    swap_readout,
    swap_test_kernel,
)
from qmlkit.kernels.matrix import (
    QuantumKernel,
    center_kernel,
    closest_psd_matrix,
    concentration_report,
    displace_matrix,
    flip_matrix,
    geometric_difference,
    is_psd,
    kernel_matrix,
    kernel_shot_cost,
    kernel_spread,
    min_eigenvalue,
    normalize_kernel,
    shots_to_resolve,
    square_kernel_matrix,
    target_alignment,
    threshold_matrix,
)
from qmlkit.kernels.models import (
    QSVC,
    QSVR,
    NearestFidelityClassifier,
    TrainableKernel,
    projected_kernel_matrix,
    rkhs_model,
)

__all__ = [
    "fidelity_kernel",
    "swap_test_kernel",
    "hadamard_test",
    "swap_readout",
    "swap_probability",
    "inversion_circuit",
    "QuantumKernel",
    "kernel_matrix",
    "square_kernel_matrix",
    "is_psd",
    "min_eigenvalue",
    "threshold_matrix",
    "displace_matrix",
    "flip_matrix",
    "closest_psd_matrix",
    "center_kernel",
    "normalize_kernel",
    "target_alignment",
    "kernel_shot_cost",
    "kernel_spread",
    "shots_to_resolve",
    "concentration_report",
    "geometric_difference",
    "QSVC",
    "QSVR",
    "NearestFidelityClassifier",
    "TrainableKernel",
    "projected_kernel_matrix",
    "rkhs_model",
]
